### PR TITLE
Damage rework - Hit position & Direction

### PR DESCRIPTION
**Pull request by niefia**
- Reworked the damage system to include Hit position & direction
-  Added options to instantiate scenes at either global or local hit position 
- Added option to apply force to Rigidbodies on hits 
- Added option to spawn decal on any hitscan collision

WIP - Still need to sort melee weapons hit position

### CODE REVIEW

**Comment by Phazorknight** [comment]
Hey, wanted to check in if this is still gonna be updated or if it's ready for review?

**Comment by niefia** [comment]
It's mostly done, just want to rework bullet impact decals before merge.

Haven't been able to work on it much lately but will try and get that done today

**Comment by Phazorknight** [comment]
Hey, just gave this a bit of a test today. Overall it's working great! The bullet decal seems to work especially well.
I haven't looked into the code much but I noticed the impact particles seem to not spawn if the impact is close to the player. Let me know if thats by design.

**Review by Phazorknight — APPROVED** [review]
I want to merge in some of these features so I'm gonna approve this.

@niefia thanks so much for your work on this! If you continue to tweak this, please make a new PR from main!

**Pull request merged**
