### PR TITLE
Updating Cogito to Godot 4.3

### PR DESCRIPTION
**Pull request by Phazorknight**
This PR contains all changes related to making sure Cogito works in Godot 4.3.

### CODE REVIEW

**Comment by OvercastInteractive** [comment]
I didn't run into any errors in the two main scenes (Lobby, Laboratory) while testing out all of the systems using gamepad.

One issue (not relevant to the 4.3 update but from reorganizing cogito as an addon) I'm seeing is out-of-date icon file paths:
Cogito_Icon_References_Not_Found

Did find one issue in the legacy demo scene in which the key on the nearby shelf _wasn't_ able to open the door:
Cogito_LegacyDemoScene_Key_Unusable

**Comment by Phazorknight** [comment]
@OvercastInteractive thanks for catching these! Both should be fixed in the latest commit.

**Comment by ac-arcana** [comment]
Hey just wanted to leave a note that I do see the request for me to review, just haven't had time for any dev related stuff the next few days. I will review it in the next couple of days.

**Comment by Phazorknight** [comment]
@ac-arcana oh no rush, I've added all contributors for a review request, but technically only one approval is needed (if it's good)

**Comment by OvercastInteractive** [comment]
I was hoping to do further testing before adding a review however my graphics card has been having issues with Godot 4.3 using the Forward+ renderer (**for multiple projects not just Cogito!**) 😥

Has anyone else had this issue with Godot 4.3 using Forward+?

Cogito_4 3_ForwardPlus_Rendering_Issue_01

**Comment by Phazorknight** [comment]
> Has anyone else had this issue with Godot 4.3 using Forward+?

@OvercastInteractive Yikes. When did this start? Does this not happen on Godot 4.2? Definitely seems GPU related, might wanna update/reinstall your drivers to see if that helps.

**Comment by Phazorknight** [comment]
Giving this another bump for review! Would like to get this folded in so other PRs can be made compatible as well.

**Review by OvercastInteractive — APPROVED** [review]
Everything looks good from my end.

**Pull request merged**
