### PR TITLE
Fall/Jump Landing Audio

### PR DESCRIPTION
**Pull request by niefia**
Basic attempt at a Materials based Fall landing audio player, using the same logic as the Step audio to determine materials.

### CODE REVIEW

**Comment by Phazorknight** [comment]
hey, this is pretty cool!
Default volume seems to be quite loud, so finding a way to dampen that would be good.
I appreciate you having this separate to the footstep system, but I'd probably combine it. I don't see a case where we want to have these two as separate components.

**Comment by niefia** [comment]
There was a few reasons I did it that way but in retrospect it may not be necessary.

I put together a quick test using the FootstepPlayer only, and came across one major problem which is:
If the player goes from landing into a run, the step sounds will overwrite the landing sound

Can't think of a way to avoid this aside from using 2 nodes for it, but if you have any ideas feel free to suggest. 
I'll work on cleaning up the code a bit in the meantime

**Comment by niefia** [comment]
Ok code has been majorly cleaned up and with the last commit, it's been combined into a single AudioStreamPlayer3D node that avoids the sound overwrite problem I was having.

**Comment by Phazorknight** [comment]
I would've suggested to maybe use the included QuickAudio plug in that spawns/pools Audio players as necessary.
But will take a look at your solution in a bit.

Thanks!

**Comment by niefia** [comment]
Oh a plugin wasn't even needed, I just missed a basic Godot feature. Just needed to set the AudioStreamPlayer3D to have polyphony to fix it, so set that to 8 max now instead of 1.

**Review by Phazorknight — APPROVED** [review]
Nice job cleaning this up!
Let me know if you're still planning on working more on this PR or if it's ready to merge.

**Comment by niefia** [comment]
It's ready to merge now. Functionality seems to be perfect from testing, and just put out a last commit to improve the readability of variables and comments before it gets merged.

**Comment by Phazorknight** [comment]
Amazing work, thanks so much for this! Merging.

**Pull request merged**
